[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist"
]

[phases.build]
dependsOn = ["install"]
cmds = [
    # Descargamos FrankenPHP directamente en la carpeta del proyecto
    "curl -L https://github.com/dunglas/frankenphp/releases/latest/download/frankenphp-linux-x86_64 -o frankenphp",
    "chmod +x frankenphp",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
# Fíjate que ahora usamos ./frankenphp (ejecutable local)
cmd = "php artisan migrate --force && ./frankenphp run --config /app/Caddyfile"